# Generated by Django 4.1.6 on 2023-03-31 10:48

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Имя')),
                ('name_ru', models.CharField(max_length=70, null=True, verbose_name='Имя')),
                ('name_ky', models.CharField(max_length=70, null=True, verbose_name='Имя')),
                ('direction', models.CharField(max_length=50, verbose_name='Направление')),
                ('direction_ru', models.CharField(max_length=50, null=True, verbose_name='Направление')),
                ('direction_ky', models.CharField(max_length=50, null=True, verbose_name='Направление')),
                ('description', models.TextField(max_length=515, verbose_name='Описание')),
                ('description_ru', models.TextField(max_length=515, null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(max_length=515, null=True, verbose_name='Описание')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=123, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=123, null=True, verbose_name='Название')),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание для подраздела')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание для подраздела')),
                ('description_ky', models.TextField(blank=True, null=True, verbose_name='Описание для подраздела')),
                ('id_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='landing.section')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='Ссылка на прямой эфир')),
                ('start_time', models.DateTimeField(verbose_name='Время начала стрима')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания стрима')),
                ('is_active', models.BooleanField(verbose_name='Актуально?')),
            ],
            options={
                'verbose_name': 'Прямой эфир',
                'verbose_name_plural': 'Прямой эфир',
            },
        ),
        migrations.CreateModel(
            name='StudyingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=50, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Время обучения',
                'verbose_name_plural': 'Время обучения',
            },
        ),
        migrations.CreateModel(
            name='CourseForLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=123, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=123, null=True, verbose_name='Название')),
                ('slug', models.SlugField()),
                ('cover', models.ImageField(upload_to='media/image/', verbose_name='Обложка')),
                ('description', models.TextField(verbose_name='Описание о языке')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание о языке')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание о языке')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Информация о курсе')),
                ('additional_info_ru', models.TextField(blank=True, null=True, verbose_name='Информация о курсе')),
                ('additional_info_ky', models.TextField(blank=True, null=True, verbose_name='Информация о курсе')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('format', models.ManyToManyField(to='srm.learningformat', verbose_name='Формат обучения')),
                ('studying_time', models.ManyToManyField(to='landing.studyingtime', verbose_name='Время обучения')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='srm.employee', verbose_name='Ментор')),
            ],
            options={
                'verbose_name': 'Курс для Лэндинга',
                'verbose_name_plural': 'Курс для Лэндинга',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=80, verbose_name='Название темы')),
                ('topic_name_ru', models.CharField(max_length=80, null=True, verbose_name='Название темы')),
                ('topic_name_ky', models.CharField(max_length=80, null=True, verbose_name='Название темы')),
                ('slug', models.SlugField()),
                ('body', ckeditor.fields.RichTextField(verbose_name='Контент')),
                ('body_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Контент')),
                ('body_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Контент')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.section', verbose_name='Раздел')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ментор')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionToCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.section', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка на курс',
                'verbose_name_plural': 'Подписка на курс',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
