# Generated by Django 4.1.6 on 2023-02-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='topic_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
