# Generated by Django 4.1.6 on 2023-03-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='start_time',
            field=models.DateTimeField(verbose_name='Время начала стрима'),
        ),
    ]
