# Generated by Django 4.1.6 on 2023-03-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_subscriptiontocourse_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiontocourse',
            name='is_active',
        ),
        migrations.AddField(
            model_name='stream',
            name='is_active',
            field=models.BooleanField(default=1, verbose_name='Актуально?'),
            preserve_default=False,
        ),
    ]
