# Generated by Django 4.1.6 on 2023-04-10 12:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
        migrations.AlterUniqueTogether(
            name='accessrights',
            unique_together={('user',)},
        ),
    ]
