# Generated by Django 4.1.6 on 2023-04-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_question_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrights',
            name='start_date',
        ),
        migrations.AddField(
            model_name='accessrights',
            name='is_ban_forever',
            field=models.BooleanField(default=False, verbose_name='Забанить навсегда'),
        ),
        migrations.AlterField(
            model_name='accessrights',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Конец даты бана'),
        ),
    ]
