# Generated by Django 4.1.6 on 2023-04-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_accessrights_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body_ky',
            field=models.TextField(null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='comment',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='question',
            name='body_ky',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='question',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='question',
            name='title_ky',
            field=models.CharField(max_length=225, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='question',
            name='title_ru',
            field=models.CharField(max_length=225, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='topic',
            name='title_ky',
            field=models.CharField(max_length=123, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='topic',
            name='title_ru',
            field=models.CharField(max_length=123, null=True, verbose_name='Название'),
        ),
    ]
