# Generated by Django 4.1.6 on 2023-02-23 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_time',
            field=models.TimeField(default=datetime.time(19, 1, 28, 727778), verbose_name='Время сдачи'),
        ),
    ]
