# Generated by Django 4.1.6 on 2023-03-31 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_time',
            field=models.TimeField(default=datetime.time(16, 48, 19, 599390), verbose_name='Время сдачи'),
        ),
    ]
