# Generated by Django 4.1.6 on 2023-03-04 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_time',
            field=models.TimeField(default=datetime.time(0, 58, 10, 704430), verbose_name='Время сдачи'),
        ),
    ]
