# Generated by Django 4.1.6 on 2023-03-31 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_assignment_due_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_time',
            field=models.TimeField(default=datetime.time(16, 48, 26, 592431), verbose_name='Время сдачи'),
        ),
    ]
