# Generated by Django 4.1.6 on 2023-04-06 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_alter_assignment_due_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_time',
            field=models.TimeField(default=datetime.time(1, 3, 1, 49679), verbose_name='Время сдачи'),
        ),
    ]
