# Generated by Django 4.1.6 on 2023-04-10 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_alter_assignment_due_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_time',
            field=models.TimeField(default=datetime.time(18, 13, 4, 231213), verbose_name='Время сдачи'),
        ),
    ]
