# Generated by Django 4.1.6 on 2023-02-23 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_alter_assignment_due_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_time',
            field=models.TimeField(default=datetime.time(22, 19, 25, 390850), verbose_name='Время сдачи'),
        ),
    ]
