# Generated by Django 4.1.6 on 2023-04-12 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_alter_assignment_due_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_time',
            field=models.TimeField(default=datetime.time(23, 45, 36, 397316), verbose_name='Время сдачи'),
        ),
    ]
