# Generated by Django 4.1.6 on 2023-02-28 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_alter_assignment_due_time_remove_teacher_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_time',
            field=models.TimeField(default=datetime.time(15, 24, 47, 601787), verbose_name='Время сдачи'),
        ),
    ]
