# Generated by Django 4.1.6 on 2023-02-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='flow_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Постоянный'), (2, 'Одноразовый'), (3, 'Сотрудник'), (4, 'Возврат')], verbose_name='Тип расхода'),
        ),
    ]
