# Generated by Django 4.1.6 on 2023-02-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0002_alter_expense_flow_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='prepayment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
