# Generated by Django 4.1.6 on 2023-02-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0004_alter_lead_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_prepayment',
            field=models.BooleanField(default=False, verbose_name='Заплатил предоплату?'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='prepayment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Предоплата'),
        ),
    ]
