# Generated by Django 4.1.6 on 2023-02-23 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0005_lead_is_prepayment_alter_lead_prepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='srm.learningformat', verbose_name='Формат обучения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studying_time',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Утро'), (2, 'День'), (3, 'Вечер'), (4, 'Ночь')], null=True, verbose_name='Время обучения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='srm.employee', verbose_name='Ментор'),
        ),
    ]
