# Generated by Django 4.1.6 on 2023-02-23 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0007_remove_lead_is_prepayment_remove_lead_prepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srm.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='income',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='srm.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='income',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='srm.paymentmethod', verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='income',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srm.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='srm.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='srm.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='student',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='srm.learningformat', verbose_name='Формат обучения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='srm.employee', verbose_name='Ментор'),
        ),
    ]
